import type { LevelDefinition, MaterialDefinition, MemberKind } from "../types";

const materials: Record<MemberKind, MaterialDefinition> = {
  deck: {
    kind: "deck",
    label: "Road deck",
    costPerMeter: 500,
    density: 2,
    maxLength: 2,
    tensileStrength: 450,
    compressiveStrength: 820,
    shearStrength: 112,
    bendingStrength: 390,
    color: 0xf2b84b,
  },
  steel: {
    kind: "steel",
    label: "Steel truss",
    costPerMeter: 300,
    density: 0.25,
    maxLength: 2.5,
    tensileStrength: 165,
    compressiveStrength: 135,
    shearStrength: 135,
    bendingStrength: 0,
    color: 0x69c6d9,
  },
  concrete: {
    kind: "concrete",
    label: "Concrete beam",
    costPerMeter: 420,
    density: 2.4,
    maxLength: 2,
    tensileStrength: 85,
    compressiveStrength: 980,
    shearStrength: 175,
    bendingStrength: 230,
    color: 0xaeb7c2,
  },
  wood: {
    kind: "wood",
    label: "Timber beam",
    costPerMeter: 210,
    density: 0.55,
    maxLength: 2.5,
    tensileStrength: 120,
    compressiveStrength: 95,
    shearStrength: 72,
    bendingStrength: 145,
    color: 0xc9844c,
  },
  aluminum: {
    kind: "aluminum",
    label: "Aluminum truss",
    costPerMeter: 460,
    density: 0.12,
    maxLength: 3,
    tensileStrength: 135,
    compressiveStrength: 105,
    shearStrength: 105,
    bendingStrength: 0,
    color: 0xb9d9ef,
  },
  cable: {
    kind: "cable",
    label: "Tension cable",
    costPerMeter: 180,
    density: 0.05,
    maxLength: 4,
    tensileStrength: 240,
    compressiveStrength: 0,
    shearStrength: 0,
    bendingStrength: 0,
    color: 0xe77ac8,
  },
};

export const LEVELS: readonly LevelDefinition[] = [
  {
    id: "blueprint-span-01",
    title: "The Eight-Meter Test",
    canyonWidth: 8,
    gridSpacing: 1,
    budget: 10_000,
    buildBounds: { minX: 0, maxX: 8, minY: -4, maxY: 2 },
    viewBounds: { minX: -3.7, maxX: 11.7, minY: -5.2, maxY: 4.1 },
    anchors: [
      { id: "road-left", x: 0, y: 0, kind: "road", label: "West road" },
      { id: "road-right", x: 8, y: 0, kind: "road", label: "East road" },
      { id: "lower-left", x: 0, y: -2, kind: "foundation", label: "West bedrock" },
      { id: "lower-right", x: 8, y: -2, kind: "foundation", label: "East bedrock" },
    ],
    materials,
    physics: { gravity: -9.81, nodeMass: 0.35, steelFrequencyHz: 15, steelDampingRatio: 0.7 },
    truck: {
      start: { x: -2.3, y: 0.65 },
      chassisHalfWidth: 0.67,
      chassisHalfHeight: 0.19,
      chassisDensity: 2.6,
      wheelRadius: 0.235,
      wheelOffsetX: 0.43,
      wheelOffsetY: -0.28,
      wheelDensity: 1.1,
      suspensionFrequencyHz: 5,
      suspensionDampingRatio: 0.72,
      targetSpeed: 1.65,
      maxMotorTorque: 34,
      startDelay: 1,
      finishX: 9.25,
      fallY: -4.65,
      timeout: 30,
      stallWindow: 3,
      minimumProgress: 0.15,
    },
  },
  {
    id: "blueprint-span-02",
    title: "The Twelve-Meter Divide",
    canyonWidth: 12,
    gridSpacing: 1,
    budget: 14_500,
    buildBounds: { minX: 0, maxX: 12, minY: -5, maxY: 3 },
    viewBounds: { minX: -3.7, maxX: 15.7, minY: -6.2, maxY: 5.1 },
    anchors: [
      { id: "road-left", x: 0, y: 0, kind: "road", label: "West road" },
      { id: "road-right", x: 12, y: 0, kind: "road", label: "East road" },
      { id: "lower-left", x: 0, y: -3, kind: "foundation", label: "West bedrock" },
      { id: "mid-pillar", x: 6, y: -2, kind: "foundation", label: "River pillar" },
      { id: "lower-right", x: 12, y: -3, kind: "foundation", label: "East bedrock" },
    ],
    materials,
    physics: { gravity: -9.81, nodeMass: 0.38, steelFrequencyHz: 15, steelDampingRatio: 0.7 },
    truck: {
      start: { x: -2.3, y: 0.65 },
      chassisHalfWidth: 0.72,
      chassisHalfHeight: 0.21,
      chassisDensity: 3,
      wheelRadius: 0.25,
      wheelOffsetX: 0.47,
      wheelOffsetY: -0.3,
      wheelDensity: 1.2,
      suspensionFrequencyHz: 5,
      suspensionDampingRatio: 0.72,
      targetSpeed: 1.8,
      maxMotorTorque: 38,
      startDelay: 1,
      finishX: 13.25,
      fallY: -5.65,
      timeout: 36,
      stallWindow: 3,
      minimumProgress: 0.15,
    },
  },
];

export const LEVEL_BY_ID = new Map(LEVELS.map((level) => [level.id, level]));
